payapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('transfers/', views.transfers, name='transfers'),
    path('requests/', views.payment_requests, name='requests'),
    path('make_request/', views.make_request, name='make_request'),
    path('accept_request/<int:request_id>/', views.accept_request, name='accept_request'),
    path('decline_request/<int:request_id>/', views.decline_request, name='decline_request'),
    path('cancel_request/<int:request_id>/', views.cancel_request, name='cancel_request'),
    path('send_payment/', views.send_payment, name='send_payment'),
    path('notifications/', views.notifications, name='notifications'),
    path('notifications/read/<int:notification_id>/', views.mark_notification_as_read, name='mark_as_read'),
]

register/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

webapps2024/urls.py
from django.urls import path, include
import payapp.views
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='webapps2024/')),
    path('webapps2024/', include([
        path('', payapp.views.home, name='home'),
        path('register/', include(('register.urls', 'register'), namespace='register')),
        path('', include(('payapp.urls', 'payapp'), namespace='payapp')),
        path('admin/', include(('custom_admin.urls', 'custom_admin'), namespace='admin')),
        path('conversion/', include(('conversion.urls', 'conversion'), namespace='conversion')),
    ]))
]

payapp/forms.py
from django import forms
from django.contrib.auth.models import User

from payapp.models import Request, Account, Transfer


class RequestForm(forms.ModelForm):
    """
    Form to request money from another user
    """
    receiver = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Request
        fields = ['receiver', 'amount']
        widgets = {
            'receiver': forms.TextInput(attrs={'class': 'form-control'}),
            'amount': forms.NumberInput(attrs={'class': 'form-control', 'step': '0.01', 'autocomplete': 'off',
                                               'min': '0.01'})
        }

    def __init__(self, *args, **kwargs):
        """
        Constructor to set the label of the amount field to the user's currency
        :param args:
        :param kwargs:
        """
        user_currency = kwargs.pop('user_currency', None)  # get the user's currency
        super(RequestForm, self).__init__(*args, **kwargs)
        if user_currency:  # if the user's currency is known
            self.fields['amount'].label = f"Amount (in {user_currency.upper()})"  # set the label to the user's currency

    def clean_receiver(self):
        username = self.cleaned_data.get('receiver')
        try:
            user = User.objects.get(username=username)
            account = Account.objects.get(user=user)
            return account
        except User.DoesNotExist:
            raise forms.ValidationError("User does not exist.")


class PaymentForm(forms.ModelForm):
    """
    Form to make a payment to another user
    """
    receiver = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        """
        Meta Class to specify the model and fields to be used in the form
        """
        model = Transfer
        fields = ['receiver', 'amount']
        widgets = {
            'receiver': forms.TextInput(attrs={'class': 'form-control'}),
            'amount': forms.NumberInput(attrs={'class': 'form-control', 'step': '0.01', 'autocomplete': 'off',
                                               'min': '0.01'}),
        }

    def __init__(self, *args, **kwargs):
        """
        Constructor to set the label of the amount field to the user's currency
        :param args:
        :param kwargs:
        """
        user_currency = kwargs.pop('user_currency', None)  # get the user's currency
        super(PaymentForm, self).__init__(*args, **kwargs)
        if user_currency:  # if the user's currency is known
            self.fields['amount'].label = f"Amount (in {user_currency.upper()})"  # set the label to the user's currency

    def clean_receiver(self):
        username = self.cleaned_data.get('receiver')
        try:
            user = User.objects.get(username=username)
            account = Account.objects.get(user=user)
            return account
        except User.DoesNotExist:
            raise forms.ValidationError("User does not exist.")

payapp/views.py
from datetime import datetime

from django.contrib import messages
from django.contrib.auth.models import User
from django.db.models import Q
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404
from payapp.custom_exceptions import InsufficientBalanceException
from payapp.forms import RequestForm, PaymentForm
from payapp.models import Transfer, Account, Request, Notification
from webapps2024 import settings
from django.db import transaction
from thrift_timestamp.client import ThriftTimestampClient

currency_symbols = {
    'USD': '$',
    'GBP': '£',
    'EUR': '€'
}


def login_required_message(function):
    """
    Decorator to display a message if the user is not logged in
    """

    def wrap(request, *args, **kwargs):
        # If the user is logged in, call the function
        if request.user.is_authenticated:
            return function(request, *args, **kwargs)

        # If the user is not logged in, display an error message and redirect to the login page
        else:
            messages.error(request, "You need to be logged in to view this page.")
            return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))

    # Retains the docstring and name of the original function
    wrap.__doc__ = function.__doc__
    wrap.__name__ = function.__name__
    return wrap


def home(request):
    """
    View function to display the home page
    :param request:
    :return:
    """
    # Gets the current timestamp for the dashboard
    timestamp = ThriftTimestampClient().get_current_timestamp()
    # Converts the timestamp to a datetime object
    timestamp = datetime.strptime(timestamp, '%Y-%m-%d %H:%M:%S')

    return render(request, 'payapp/home.html', {'timestamp': timestamp})


@login_required_message
def transfers(request):
    """
    View function to display the transfers of the logged-in user with login required decorator

    :param request:
    :return:
    """
    transfer_list = (Transfer.objects.filter(
        Q(sender__user=request.user) | Q(receiver__user=request.user)
    ))
    if transfer_list.exists():
        transfer_list = transfer_list.select_related('sender', 'receiver', 'sender__user',
                                                     'receiver__user').order_by('-created_at')
    return render(request, 'payapp/transfers.html', {'transfers': transfer_list})


@login_required_message
def payment_requests(request):
    """
    View function to display the requests of the logged-in user

    :param request:
    :return:
    """
    # Select outgoing requests where the status is pending
    outgoing_request_list = (Request.objects.filter(
        Q(sender__user=request.user, status='pending')
    ))
    # Checks that the outgoing request list is not empty as cannot select_related on an empty queryset
    if outgoing_request_list.exists():
        outgoing_request_list = (outgoing_request_list.select_related('sender', 'receiver', 'sender__user',
                                                                      'receiver__user')
                                 .order_by('-created_at'))
    # Select incoming requests where the status is pending
    incoming_request_list = Request.objects.filter(
        Q(receiver__user=request.user, status='pending')
    )
    if incoming_request_list.exists():
        (incoming_request_list.select_related('sender', 'receiver', 'sender__user', 'receiver__user')
         .order_by('-created_at'))
    # Select completed requests from transaction table where the sender or receiver is the logged-in user

    completed_request_list = (Request.objects.filter(
        (Q(sender__user=request.user) & ~Q(status='pending')) |
        (Q(receiver__user=request.user) & ~Q(status='pending'))
    ))
    if completed_request_list.exists():
        completed_request_list = completed_request_list.select_related('sender', 'receiver', 'sender__user',
                                                                       'receiver__user').order_by('-created_at')

    # Render the requests page with the context
    context = {'outgoing_requests': outgoing_request_list, 'incoming_requests': incoming_request_list,
               'completed_requests': completed_request_list}
    return render(request, 'payapp/requests.html', context)


@login_required_message
def make_request(request):
    """
    View function to handle the request of a new user

    :param request:
    :return:
    """
    user = request.user
    account = Account.objects.get(user=user)
    # If the form is submitted, validate the form and save the request
    if request.method == 'POST':
        form = RequestForm(request.POST, user_currency=account.currency)  # Passes currency for constructor
        # If the form is valid, save the request
        if form.is_valid():
            try:
                # Checks if the amount is positive, if not, display an error message and return the form
                if form.cleaned_data.get('amount') <= 0:
                    messages.error(request, "You must request a positive sum. Please try again.")
                    return render(request, 'payapp/make_request.html', {'form': form})

                with transaction.atomic():  # Ensures that the request is saved in the same transaction as the sender
                    # and receiver accounts to maintain atomicity
                    request_instance = form.save(commit=False)  # Creates an instance of the form without saving it
                    request_instance.sender = Account.objects.get(user=request.user)
                    request_instance.receiver = Account.objects.get(user__username=request.POST['receiver'])

                    # If the receiver is not the sender, save the request
                    if request_instance.receiver != request_instance.sender:
                        request_instance.save()
                        # Adds a notification to the receiver's account
                        Notification.objects.create(
                            to_user=request_instance.receiver,
                            from_user=request_instance.sender,
                            message=f"{request_instance.sender.user.username} has requested "
                                    f"{currency_symbols.get(request_instance.sender.currency.upper())}"
                                    f"{request_instance.amount}",
                            notification_type='request_sent',
                            created_at=request_instance.created_at,
                            request=request_instance
                        )
                        messages.success(request, "Request has been made")

                    # If the receiver is the sender, display an error message and return the form
                    else:
                        messages.error(request, "You cannot request money from yourself! Please try again.")
                        return render(request, 'payapp/make_request.html', {'form': form})
                    return redirect('home')
            # If the user does not exist, display an error message and return the form
            except User.DoesNotExist as e:
                messages.error(request, "The user does not exist. Please make sure you spelled their username"
                                        " correctly and try again.")
                return render(request, 'payapp/make_request.html', {'form': form})

        # If the form is invalid, display an error message and return the form
        else:
            messages.error(request, "Invalid information. Please try again.")
            return render(request, 'payapp/make_request.html', {'form': form})
    # If the form is not submitted, display the form
    else:
        form = RequestForm(user_currency=account.currency)
        return render(request, 'payapp/make_request.html', {'form': form})


@login_required_message
def accept_request(request, request_id):
    """
    View function to accept a request from another user


    :param request:
    :param request_id: The id of the request object
    :return:
    """
    # Try to accept the request
    with transaction.atomic():
        try:
            req = get_object_or_404(Request, id=request_id)
            req.accept_request(req.amount)
            # Adds a notification to the sender's account
            Notification.objects.create(
                to_user=req.sender,
                from_user=req.receiver,
                message=f"Your request for {currency_symbols.get(req.sender.currency.upper())}{req.amount} from "
                        f"{req.receiver.user.username} has been accepted.",
                notification_type='request_accepted',
                created_at=req.created_at,
                request=req
            )
            # Marks the request sent notification as read
            request_notification = Notification.objects.get(request=req, notification_type='request_sent')
            request_notification.mark_as_read()
            messages.success(request, "Request has been accepted")
            return redirect('payapp:requests')

        # If the request does not exist, display an error message and redirect to the requests page
        except Http404:
            messages.error(request, "The requested item does not exist.")
            return redirect('payapp:requests')

        # If the user does not have enough balance to accept the request, display an error message and
        # redirect to the requests page
        except InsufficientBalanceException as e:
            messages.error(request, "You do not have enough balance to accept this request. "
                                    "Please add funds to your account.")
            return redirect('payapp:requests')

        # If the user tries to accept a negative number, display an error message and redirect to the requests page
        except ValueError as e:

templates/payapp/admin_all_transactions.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Admin - All Transactions{% endblock title %}</title>
</head>
{% block content %}
<body>
    <h1>All Transactions</h1>
    <p> There {{ transactions.count | pluralize:'is, are'}} currently {{ transactions.count }} completed 
        transaction{{ transactions.count | pluralize }}.</p>
    <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover table-sm">
            <thead  class="text-center">
                <tr>
                    <th>Transaction ID</th>
                    <th>Amount (in {{ user_currency | upper}})</th> <!-- uses currency context processor to get user currency -->
                    <th>From User</th>
                    <th>To User</th>
                    <th>Date</th>
                </tr>
            </thead>
            <tbody class="text-center">
                {% for transaction in transactions %}
                <tr>
                    <td>{{ transaction.id }}</td>
                    <td>{{ transaction.amount }}</td>
                    <td>{{ transaction.sender.user.username }}</td>
                    <td>{{ transaction.receiver.user.username }}</td>
                    <td>{{ transaction.created_at | date:"D, d M Y H:i" }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content %}
</body>

</html>

templates/payapp/admin_all_users.html
{% extends 'base.html' %}
{% load group_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Admin - All Users {% endblock title %}</title>
</head>
<body>
{% block content %}
    <h1>All Users</h1>
    There {% if admins.count|add:users.count == 1 %}is{% else %}are{% endif %} currently {{ admins.count|add:users.count }} 
    user{{admins.count|add:users.count|pluralize }}.
    {{ admins.count }} of which {{ admins.count |pluralize:'is,are' }} admin{{ admins.count|pluralize }}.
    <br>
    <h2>Administrators</h2>
    {% if admins %}
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover table-sm">
                <thead  class="text-center">
                <tr>
                    <th>Username</th>
                    <th>Email</th>
                    <th>Last Login</th>
                </tr>
                </thead>
                <tbody class="text-center">
                {% for admin in admins %}
                    <tr>
                        <td>{{ admin.user.username }}</td>
                        <td>{{ admin.user.email }}</td>
                        <td>{{ admin.user.last_login }}</td>
                    </tr>
                {% endfor %}
                </tbody>
        </table>
    </div>
    {% endif %}
    <br>
    {% if users %}
    <h2>Users</h2>
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover table-sm">
                <thead  class="text-center">
                <tr>
                    <th>Username</th>
                    <th>Email</th>
                    <th>Last Login</th>
                </tr>
                </thead>
                <tbody class="text-center">
                {% for user in users %}
                    <tr>
                        <td>{{ user.user.username }}</td>
                        <td>{{ user.user.email }}</td>
                        <td>{{ user.user.last_login }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    {% endif %}
    <br>
    <p> To register a new admin, click <a href="{% url 'custom_admin:register' %}">here</a>.</p>
{% endblock %}

</body>
</html>

templates/payapp/home.html
{% extends "base.html" %}
{% load currency_filters %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Homepage{% endblock title %}</title>
</head>
<body>
{% block content %}
    {% if user.is_authenticated %}
        <p>
            Welcome, <b>{{ user.username }}</b>, to the FakePal homepage!
        You currently have {{ user.account.currency | currency_symbol}}{{ user.account.balance }}  in your account.<br>
        It is currently <b>{{ timestamp | time:"g:i:s a" }}</b> on the <b>{{ timestamp | date:"D,d F, Y" }}</b>.
        </p>
    {% else %}
        <p>
        Please <a href="{% url 'register:login' %}">login</a> to access the FakePal homepage or <a 
                href="{% url "register:register" %}">register</a> if you don't have an account.
        </p>
    {% endif %}
    
{% endblock content %}
</body>
</html>

templates/payapp/make_request.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %} Request a Payment{% endblock title %}</title>
    </head>
    <body>
        {% block content %}
        <h2>Make a Payment Request</h2>
        <form method="post">
            {% csrf_token %}
            {{form |crispy }}
            <input type="submit" value="Submit" class="btn btn-primary btn-block btn-lg">
        </form>
        {% endblock content %}
    </body>
</html>

templates/payapp/notifications.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        {% block title %} Notifications{% endblock title %}
        {% block extra_css %}<link rel="stylesheet" href="{% static 'payapp/css/notifications.css' %}">{% endblock %}

    </head>
    <body>
        {% block content %}
        {% if notifications|length == 0 %}
            <p>You have no unread notifications.</p>
        {% else %}:
            <h1>All Notifications</h1>
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-hover table-sm">

                    <thead  class="text-center">
                        <tr>
                            <th>Notification</th>
                            <th>Time</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for notification in notifications %}
                        <tr class="text-center">

                            <td><a class=" notification_link"  
                                   href="{% url 'payapp:mark_as_read' notification.id %}">
                                {{ notification.message }}</a>
                            </td>
                            <td>{{ notification.created_at }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
            </table>
        </div>
        {% endif %}
        {% endblock content %}
    </body>
</html>

templates/payapp/requests.html
{% extends 'base.html' %}
{% load currency_filters %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Payment Requests {% endblock title %}</title>
</head>

<body>
{% block content %}
    <h1>Requests</h1>
    <br>
    <h2>Pending Requests</h2>
    <h3>Incoming Requests</h3>
    {% if incoming_requests %}
        <p> You currently have {{ incoming_requests.count }} incoming payment 
            request{{ incoming_requests | pluralize }}:</p>
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover table-sm">
                <thead  class="text-center">
                <tr>
                    <th>Request ID</th>
                    <th>Amount</th>
                    <th>From User</th>
                    <th>Date</th>
                    <th>Status</th>
                    <th>Accept or Deny</th>
                </tr>
                </thead>
                <tbody>
                {% for request in incoming_requests %}
                    <tr class="text-center">
                        <td>{{ request.id }}</td>
                        <td>{{ request.sender.currency|currency_symbol }}{{ request.amount }} </td>
                        <td>{{ request.sender.user.username }}</td>
                        <td>{{ request.created_at }}</td>
                        <td>{{ request.status|capfirst }}</td>
                        <td class="text-center">
                            <form action="{% url 'payapp:accept_request' request.id %}" method="post"
                                  class="d-inline-block">
                                {% csrf_token %}
                                <input type="hidden" name="amount" value="{{ request.amount }}">
                                <button type="submit" class="btn btn-success btn-sm">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="5vh" height="5vh" fill="white" 
                                         class="bi bi-check" viewBox="0 0 16 16">
                                        <path d="M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 
                                        4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 
                                        1.06-1.06l2.094 2.093 3.473-4.425z"></path>
                                    </svg></button>
                            </form>
                            <form action="{% url 'payapp:decline_request' request.id %}" method="post"
                                  class="d-inline-block">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger btn-sm">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="5vh" height="5vh" fill="white"
                                         class="bi bi-x" viewBox="0 0 16 16">
                                        <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 
                                        1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 
                                        1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708"></path>
                                    </svg></button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
        </table>
    </div>
    {% else %}
        <p>You have no pending incoming payment requests.</p>
    {% endif %}
    <br>
    <h3>Outgoing Requests</h3>
    {% if outgoing_requests %}
        <p> You currently have {{ outgoing_requests.count }} outgoing payment 
            request{{ outgoing_requests | pluralize }}:</p>
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover table-sm">
                <thead class="text-center">
                    <tr>
                        <th>Request ID</th>
                        <th>Amount (in {{ user_currency |upper}})</th>
                        <th>To User</th>
                        <th>Date</th>
                        <th>Status</th>
                        <th>Cancel?</th>
                    </tr>
                </thead>
                <tbody class="text-center">
                    {% for request in outgoing_requests %}
                        <tr>
                            <td>{{ request.id }}</td>
                            <td>{{ request.amount }}</td>
                            <td>{{ request.receiver.user.username }}</td>
                            <td>{{ request.created_at }}</td>
                            <td>{{ request.status |capfirst}}</td>
                            <td class="text-center" >
                                <form action="{% url 'payapp:cancel_request' request.id %}" method="post"
                                      class="d-inline-block">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-danger btn-sm">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="5vh" height="5vh" fill="white"
                                                                                              class="bi bi-x" 
                                             viewBox="0 0 16 16">
                                        <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 
                                        1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 
                                        0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708"></path>
                                    </svg></button>
                                </form>
                            </td>
                        </tr>
            {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
        <p>You have no pending outgoing payment requests.</p>
    {% endif %}
    <br>
    <h2>Completed Requests</h2>
    {% if completed_requests %}
        <p> You currently have {{ completed_requests.count }} completed payment
            request{{ completed_requests | pluralize }}:</p>
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover table-sm">
                <thead  class="text-center">
                    <tr>
                        <th>Request ID</th>
                        <th>Amount</th>
                        <th>From User</th>
                        <th>To User</th>
                        <th>Date</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody class="text-center">
                    {% for request in completed_requests %}
                        <tr>
                            <td>{{ request.id }}</td>
                            <td>{{ request.sender.currency|currency_symbol }}{{ request.amount }}</td> <! -- currency filter -->
                            <td>{{ request.sender.user.username }}</td>
                            <td>{{ request.receiver.user.username }}</td>
                            <td>{{ request.created_at }}</td>
                            <td>{{ request.status |capfirst }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
        <p>You have no completed payment requests.</p>
    {% endif %}
    <br>
<p>Click <a href="{% url 'payapp:make_request' %}">here</a> to make a new request. </p>
{% endblock content %}

</body>
</html>

templates/payapp/send_payment.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Send a Payment{% endblock title %}</title>
</head>
<body>
{% block content %}
    <h2>Send a Payment</h2>
    <form method="post">
        {% csrf_token %}
        {{form |crispy }}
        <input type="submit" class="btn btn-primary btn-block btn-lg" value="Submit">
    </form>
{% endblock content %}
</body>
</html>

templates/payapp/transfers.html
{% extends 'payapp/../base.html' %}
{% load currency_filters %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Transfers {% endblock %}</title>
</head>
<body>
{% block content %}
    <h1>Transfers</h1>
    {% if transfers %}
        <p>
            You have
            {{ transfers|length }} completed
            transfer{{ transfers|length|pluralize }}.
        </p>
        <div class="table-responsive">
                <table class="table table-striped table-bordered table-hover table-sm">
                    <thead  class="text-center">
                        <tr>
                            <th>Transfer ID</th>
                            <th>Amount</th>
                            <th>From User</th>
                            <th>To User</th>
                            <th>Transaction Date</th>
                        </tr>
                    </thead>
                    <tbody class="text-center">
                        {% for transfer in transfers %}
                            <tr>
                                <td>{{ transfer.id }}</td>
                                <td>{{ transfer.sender.currency|currency_symbol }}
                                    {{ transfer.amount }}</td> <! -- currency filter -->
                                <td>{{ transfer.sender.user.username }}</td>
                                <td>{{ transfer.receiver.user.username }}</td>
                                <td>{{ transfer.created_at | date:"D, d M Y H:i" }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
            </table>
        </div>
        
    {% else %}
        <p>You have no completed transactions.</p>
    {% endif %}
    
{% endblock %}
</body>
</html>